// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const firefox = require('selenium-webdriver/firefox')

describe('CrearCitaCliente', function() {
  jest.setTimeout(60000)
  let driver
  let vars
  
  beforeEach(async function() {
    const options = new firefox.Options()
    options.setBinary('/usr/bin/firefox-esr')
    options.addArguments('--headless')
    options.addArguments('--no-sandbox')
    options.addArguments('--disable-dev-shm-usage')
    options.addArguments('--width=1920')
    options.addArguments('--height=1080')
    options.setAcceptInsecureCerts(true)

    driver = await new Builder()
      .forBrowser('firefox')
      .setFirefoxOptions(options)
      .build()
    vars = {}
  })

  afterEach(async function() {
    if (driver) await driver.quit();
  })

  it('CrearCitaCliente', async function() {
    // 1. Cargar página y Login
    await driver.get("https://10.6.131.134/login")
    await driver.wait(until.elementLocated(By.css(".w-full:nth-child(1)")), 10000)
    await driver.findElement(By.css(".w-full:nth-child(1)")).sendKeys("nano@ull.es")
    await driver.findElement(By.css(".w-full:nth-child(2)")).sendKeys("123456")
    await driver.findElement(By.css("button[type='submit']")).click()
    
    // 2. Ir a Reservar
    await driver.sleep(3000)
    const linkReservar = await driver.wait(until.elementLocated(By.linkText("Reservar cita")), 10000)
    await linkReservar.click()
    
    // 3. Seleccionar Fisio (Primer Select)
    await driver.sleep(2000)
    // Buscamos cualquier select que NO tenga valor o sea el primero
    const selects = await driver.wait(until.elementsLocated(By.css("select")), 10000);
    
    // Click en el primer select (Fisio)
    await selects[0].click();
    await driver.sleep(500);
    // Seleccionamos la opción que contiene "fisio"
    await driver.findElement(By.xpath("//option[contains(text(), 'fisio')]")).click();

    // 4. Seleccionar Duración/Tipo (Segundo Select)
    // Es crítico seleccionar esto si la app lo requiere para habilitar el botón
    if (selects.length > 1) {
        await selects[1].click();
        await driver.sleep(500);
        // Seleccionamos la segunda opción disponible (índice 2 porque 1 suele ser el placeholder)
        await driver.findElement(By.css("select:nth-of-type(2) option:nth-child(2)")).click();
    }

    // 5. Botón Buscar (Lupa)
    // ESTRATEGIA NUEVA: No buscamos por color. Buscamos por estructura.
    // Buscamos el botón que está al lado de los selects.
    await driver.sleep(1000);
    
    let btnBuscar;
    try {
        // Intento A: Botón que contiene un SVG (icono de lupa)
        btnBuscar = await driver.findElement(By.xpath("//button[.//svg]"));
    } catch (e) {
        // Intento B: Si no tiene SVG, buscamos el tercer elemento del grid (inputs + boton)
        // Buscamos un botón genérico que no sea de texto plano
        btnBuscar = await driver.findElement(By.css("button.rounded-md"));
    }
    
    // Scroll para asegurar que es visible y click
    await driver.executeScript("arguments[0].scrollIntoView(true);", btnBuscar);
    await driver.sleep(500);
    await btnBuscar.click();
    
    // 6. Seleccionar Slot en Calendario
    await driver.sleep(2000);
    // Buscamos un div con borde verde/gris que indica disponibilidad
    // Usamos un selector CSS genérico para celdas del grid con borde
    const slotSelector = By.css(".grid > div.border.cursor-pointer, .grid > div.border.hover\\:bg-gray-50");
    const slot = await driver.wait(until.elementLocated(slotSelector), 10000);
    
    await driver.executeScript("arguments[0].scrollIntoView({block: 'center'});", slot);
    await driver.sleep(500);
    await slot.click();
    
    // 7. Escribir Motivo
    const inputSelector = By.css("input[type='text'], textarea");
    const inputMotivo = await driver.wait(until.elementLocated(inputSelector), 10000);
    await driver.wait(until.elementIsVisible(inputMotivo), 5000);
    
    await inputMotivo.click();
    await inputMotivo.sendKeys("Prueba automática Selenium");

    // 8. Confirmar (Botón verde/teal del modal)
    const btnConfirmar = await driver.findElement(By.xpath("//button[contains(text(), 'Confirmar') or contains(text(), 'Reservar')]"));
    await btnConfirmar.click();
    
    // 9. Finalizar test
    await driver.sleep(3000);
  })
})
